In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# data=pd.read_csv('/content/drive/MyDrive/Cloud Project/water_potability.csv')
data=pd.read_csv('water_potability.csv')
data.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [4]:
data.shape

(3276, 10)

In [5]:
data['ph'].unique()
data['Sulfate'].unique()
data['Trihalomethanes'].unique()

array([86.99097046, 56.32907628, 66.42009251, ..., 69.84540029,
       77.4882131 , 78.69844633])

In [6]:
data.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [7]:
data.dropna(inplace=True)

In [8]:
# mean_value=data['ph'].mean()
# data['ph'].fillna(value=mean_value, inplace=True)

In [9]:
# mean_value=data['Sulfate'].mean()
# data['Sulfate'].fillna(value=mean_value, inplace=True)

In [10]:
# mean_value=data['Trihalomethanes'].mean()
# data['Trihalomethanes'].fillna(value=mean_value, inplace=True)

In [11]:
data

ph    Hardness        Solids  Chloramines     Sulfate  \
3      8.316766  214.373394  22018.417441     8.059332  356.886136   
4      9.092223  181.101509  17978.986339     6.546600  310.135738   
5      5.584087  188.313324  28748.687739     7.544869  326.678363   
6     10.223862  248.071735  28749.716544     7.513408  393.663396   
7      8.635849  203.361523  13672.091764     4.563009  303.309771   
...         ...         ...           ...          ...         ...   
3267   8.989900  215.047358  15921.412018     6.297312  312.931022   
3268   6.702547  207.321086  17246.920347     7.708117  304.510230   
3269  11.491011   94.812545  37188.826022     9.263166  258.930600   
3270   6.069616  186.659040  26138.780191     7.747547  345.700257   
3271   4.668102  193.681735  47580.991603     7.166639  359.948574   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
5       280.467916        8.399735        54.917862   2.559708           0  
6       283.651634       13.789695        84.603556   2.672989           0  
7       474.607645       12.363817        62.798309   4.401425           0  
...            ...             ...              ...        ...         ...  
3267    390.410231        9.899115        55.069304   4.613843           1  
3268    329.266002       16.217303        28.878601   3.442983           1  
3269    439.893618       16.172755        41.558501   4.369264           1  
3270    415.886955       12.067620        60.419921   3.669712           1  
3271    526.424171       13.894419        66.687695   4.435821           1  

[2011 rows x 10 columns]

In [12]:
print(data['ph'].max() , data['ph'].min())
print(data['Hardness'].max() , data['Hardness'].min() )
print(data['Solids'].max() , data['Solids'].min())
print(data['Chloramines'].max() , data['Chloramines'].min())
print(data['Sulfate'].max() , data['Sulfate'].min())
print(data['Conductivity'].max() ,data['Conductivity'].min())
print(data['Organic_carbon'].max() , data['Organic_carbon'].min())
print(data['Trihalomethanes'].max() ,data['Trihalomethanes'].min())
print(data['Turbidity'].max() ,data['Turbidity'].min())


13.999999999999998 0.2274990502021987
317.33812405558257 73.4922336890611
56488.67241273919 320.942611274359
13.127000000000002 1.3908709048851806
481.0306423059972 129.00000000000003
753.3426195583046 201.6197367551575
27.00670661116601 2.1999999999999886
124.0 8.577012932983806
6.494748555990993 1.45


In [13]:
data.isnull().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [19]:
zero  = data[data['Potability']==0]   #zero values in Potability column
one = data[data['Potability']==1]  
from sklearn.utils import resample
#minority class that  is 1, we need to upsample/increase that class so that there is no bias
#n_samples = 1998 means we want 1998 sample of class 1, since there are 1998 samples of class 0
df_minority_upsampled = resample(one, replace = True, n_samples = 1200) 
#concatenate
data= pd.concat([zero, df_minority_upsampled])

from sklearn.utils import shuffle
data = shuffle(data)

In [20]:
data.corr().abs()['Potability'].sort_values(ascending = False)

Potability         1.000000
Sulfate            0.041314
Solids             0.030199
Organic_carbon     0.028589
Chloramines        0.026740
Hardness           0.019853
Conductivity       0.019609
ph                 0.016108
Turbidity          0.004999
Trihalomethanes    0.003872
Name: Potability, dtype: float64

In [21]:
X = data.drop('Potability', axis=1)
y = data['Potability']

In [22]:
X = round(X, 2)

In [23]:
X

ph  Hardness    Solids  Chloramines  Sulfate  Conductivity  \
1345   9.00    234.84  20933.51         7.98   365.06        444.08   
406    4.73    249.67  20834.29         5.04   379.00        411.11   
3269  11.49     94.81  37188.83         9.26   258.93        439.89   
2634   7.40    229.78  28630.95         8.71   302.32        437.37   
1542   6.35     97.28  19743.15         3.40   305.43        502.92   
...     ...       ...       ...          ...      ...           ...   
309   10.04    113.83  16266.43         7.94   363.87        557.49   
170    8.29    206.16  35216.39         6.44   347.06        399.48   
2403   4.87    174.06  15222.25         5.84   412.04        333.50   
2208   8.38    156.95  21923.87         7.66   379.54        364.79   
2041   6.42    180.29  26034.53         9.71   308.96        473.06   

      Organic_carbon  Trihalomethanes  Turbidity  
1345           12.17            54.40       3.70  
406            17.77            78.82       3.16  
3269           16.17            41.56       4.37  
2634           11.93            78.58       3.80  
1542           15.09            86.55       4.53  
...              ...              ...        ...  
309            13.20            75.23       3.81  
170            16.07            79.95       3.95  
2403           15.27            68.93       3.97  
2208           11.77            62.86       3.59  
2041           17.72            57.60       3.14  

[2400 rows x 9 columns]

In [24]:
data.value_counts()

ph         Hardness    Solids        Chloramines  Sulfate     Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability
11.491011  94.812545   37188.826022  9.263166     258.930600  439.893618    16.172755       41.558501        4.369264   1             7
4.959853   215.854869  9887.830755   6.954231     379.504731  527.479694    14.326638       52.388849        3.455045   1             6
8.151249   205.847301  15661.940335  7.009437     335.622779  555.590284    14.861133       72.762585        2.799883   1             5
7.036752   210.369104  13812.410421  8.378282     342.498361  489.545055    14.823904       69.193358        3.285372   1             5
7.571684   173.008338  8835.555876   9.566105     436.294071  305.834487    11.009592       92.481885        3.920288   1             5
                                                                                                                                     ..
6.548018   176.006536  38368.012618  7.415054     278

In [25]:
data.Potability.value_counts()

0    1200
1    1200
Name: Potability, dtype: int64

In [26]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# features= X.columns
# X[features] = sc.fit_transform(X[features])

In [52]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)
rf = RandomForestClassifier()
params_rf = {'n_estimators':[100,200, 350, 500], 'min_samples_leaf':[2, 10, 30]}
grid_rf = GridSearchCV(rf, param_grid=params_rf, cv=5)
grid_rf.fit(X_train.values, y_train.values)
print("Best parameters for Random Forest:", grid_rf.best_params_)

Best parameters for Random Forest: {'min_samples_leaf': 2, 'n_estimators': 100}


In [65]:
rf = RandomForestClassifier(n_estimators=500, min_samples_leaf=2, random_state=100)

In [66]:
from sklearn.metrics import accuracy_score ,confusion_matrix , classification_report , r2_score

rf.fit(X_train.values, y_train.values)    
   
y_pred = rf.predict(X_test.values)
accuracy = accuracy_score(y_test,y_pred)

print(accuracy)

0.8125


In [67]:
rf.predict([[0,0,0,0,0,0,0,0,0]])

array([0], dtype=int64)

In [68]:
# True Positive , True Negative.....
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[198  44]
 [ 46 192]]


In [69]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.82      0.81       242
           1       0.81      0.81      0.81       238

    accuracy                           0.81       480
   macro avg       0.81      0.81      0.81       480
weighted avg       0.81      0.81      0.81       480



In [70]:
print(r2_score(y_test,y_pred))

0.24994791304951736


In [71]:
#Saving the trained model

In [72]:
import pickle
import sklearn

In [73]:
filename='trained_final.pkl'
pickle.dump(rf,open(filename,'wb'))

In [74]:
#loading the saved model
sklearn.__version__ = '1.2.2'

In [75]:
loaded_model = pickle.load(open('trained_final.pkl','rb'))


In [76]:
# input_data =(7.7,200.22,17000.234343,7.72345,356.434345,500.32545,10.343434,100.324343,3.5353434)
# input_data =(7.423088,210.046197,31073.03133,6.374709, 312.103161, 460.894212, 16.805990, 41.607907 ,3.712682)
# input_data =(11.491011,94.812545,37188.826022,9.263166,258.930600,439.893618,16.172755,41.558501,4.369264	)
input_data =(7.754884, 210.720769 ,18857.058497, 5.693752 ,376.484622 ,375.672691 ,14.708599 ,43.299820 ,5.128390)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction=loaded_model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
  print("The water is not suitable for drinking")
else:
  print("The water is suitable for drinking")

[1]
The water is suitable for drinking


In [ ]:
# input_data =(7.7,200.22,17000.234343,7.72345,356.434345,500.32545,10.343434,100.324343,3.5353434)
input_data =(7.808856,193.553212,17329.802160,8.061362,333.775777,392.449580,19.903225,66.396293,2.798243)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction=loaded_model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
  print("The water is not suitable for drinking")
else:
  print("The water is suitable for drinking")

[0]
The water is not suitable for drinking


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
lst=loaded_model.predict_proba([[7.710960,181.938126,6552.626314,5.389249,390.596392,516.284083,17.010785,58.241734,4.288947]])[0]
lst=lst.tolist()
index=max(lst)
prediction = lst.index(index)
print(prediction)
if prediction==0:
  print("Not Suitable")
else:
  print("Suitable")

0
Not Suitable


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
