In [261]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [262]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [263]:
data=pd.read_csv('/content/drive/MyDrive/Cloud Project/water_potability.csv')
data.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [264]:
data.shape

(3276, 10)

In [265]:
data['ph'].unique()
data['Sulfate'].unique()
data['Trihalomethanes'].unique()

array([86.99097046, 56.32907628, 66.42009251, ..., 69.84540029,
       77.4882131 , 78.69844633])

In [266]:
data.isnull().sum()

ph                 491
Hardness             0
Solids               0
Chloramines          0
Sulfate            781
Conductivity         0
Organic_carbon       0
Trihalomethanes    162
Turbidity            0
Potability           0
dtype: int64

In [267]:
data.dropna(inplace=True)

In [268]:
# mean_value=data['ph'].mean()
# data['ph'].fillna(value=mean_value, inplace=True)

In [269]:
# mean_value=data['Sulfate'].mean()
# data['Sulfate'].fillna(value=mean_value, inplace=True)

In [270]:
# mean_value=data['Trihalomethanes'].mean()
# data['Trihalomethanes'].fillna(value=mean_value, inplace=True)

In [271]:
data

ph    Hardness        Solids  Chloramines     Sulfate  \
3      8.316766  214.373394  22018.417441     8.059332  356.886136   
4      9.092223  181.101509  17978.986339     6.546600  310.135738   
5      5.584087  188.313324  28748.687739     7.544869  326.678363   
6     10.223862  248.071735  28749.716544     7.513408  393.663396   
7      8.635849  203.361523  13672.091764     4.563009  303.309771   
...         ...         ...           ...          ...         ...   
3267   8.989900  215.047358  15921.412018     6.297312  312.931022   
3268   6.702547  207.321086  17246.920347     7.708117  304.510230   
3269  11.491011   94.812545  37188.826022     9.263166  258.930600   
3270   6.069616  186.659040  26138.780191     7.747547  345.700257   
3271   4.668102  193.681735  47580.991603     7.166639  359.948574   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
3       363.266516       18.436524       100.341674   4.628771           0  
4       398.410813       11.558279        31.997993   4.075075           0  
5       280.467916        8.399735        54.917862   2.559708           0  
6       283.651634       13.789695        84.603556   2.672989           0  
7       474.607645       12.363817        62.798309   4.401425           0  
...            ...             ...              ...        ...         ...  
3267    390.410231        9.899115        55.069304   4.613843           1  
3268    329.266002       16.217303        28.878601   3.442983           1  
3269    439.893618       16.172755        41.558501   4.369264           1  
3270    415.886955       12.067620        60.419921   3.669712           1  
3271    526.424171       13.894419        66.687695   4.435821           1  

[2011 rows x 10 columns]

In [272]:
print(data['ph'].max() , data['ph'].min())
print(data['Hardness'].max() , data['Hardness'].min() )
print(data['Solids'].max() , data['Solids'].min())
print(data['Chloramines'].max() , data['Chloramines'].min())
print(data['Sulfate'].max() , data['Sulfate'].min())
print(data['Conductivity'].max() ,data['Conductivity'].min())
print(data['Organic_carbon'].max() , data['Organic_carbon'].min())
print(data['Trihalomethanes'].max() ,data['Trihalomethanes'].min())
print(data['Turbidity'].max() ,data['Turbidity'].min())


13.999999999999998 0.2274990502021987
317.33812405558257 73.4922336890611
56488.67241273919 320.942611274359
13.127000000000002 1.3908709048851806
481.0306423059972 129.00000000000003
753.3426195583046 201.6197367551575
27.00670661116601 2.1999999999999886
124.0 8.577012932983806
6.494748555990993 1.45


In [273]:
data.isnull().sum()

ph                 0
Hardness           0
Solids             0
Chloramines        0
Sulfate            0
Conductivity       0
Organic_carbon     0
Trihalomethanes    0
Turbidity          0
Potability         0
dtype: int64

In [274]:
zero  = data[data['Potability']==0]   #zero values in Potability column
one = data[data['Potability']==1]  
from sklearn.utils import resample
#minority class that  is 1, we need to upsample/increase that class so that there is no bias
#n_samples = 1998 means we want 1998 sample of class 1, since there are 1998 samples of class 0
df_minority_upsampled = resample(one, replace = True, n_samples = 1200) 
#concatenate
data= pd.concat([zero, df_minority_upsampled])

from sklearn.utils import shuffle
data = shuffle(data)

In [275]:
data.corr().abs()['Potability'].sort_values(ascending = False)

Potability         1.000000
Solids             0.053155
Turbidity          0.035525
Sulfate            0.025386
Conductivity       0.023294
Organic_carbon     0.018580
Trihalomethanes    0.012287
ph                 0.009382
Chloramines        0.008111
Hardness           0.003671
Name: Potability, dtype: float64

In [276]:
X = data.drop('Potability', axis=1)
y = data['Potability']

In [277]:
X = round(X, 2)

In [278]:
X

ph  Hardness    Solids  Chloramines  Sulfate  Conductivity  \
2860  7.38    199.17  17181.01         6.60   388.03        357.37   
5     5.58    188.31  28748.69         7.54   326.68        280.47   
1216  6.64    194.05  20339.02         6.03   307.95        412.58   
1941  7.71    189.00  15456.22         5.05   322.75        523.05   
1790  7.13    275.68   9480.62         8.42   295.62        383.46   
...    ...       ...       ...          ...      ...           ...   
1453  8.03    197.61  25204.67         6.50   330.55        490.82   
1899  6.88    214.73  20509.33         9.04   321.38        306.78   
1480  7.07    207.36  22523.43         8.06   343.29        503.25   
904   5.95    160.44  16898.81         6.05   367.33        451.01   
1442  6.12    181.31  15135.13         5.82   293.84        391.61   

      Organic_carbon  Trihalomethanes  Turbidity  
2860           16.95            75.89       4.01  
5               8.40            54.92       2.56  
1216           15.89            57.64       4.52  
1941           16.09            57.29       4.90  
1790           18.32            94.42       1.99  
...              ...              ...        ...  
1453           15.11            89.80       2.45  
1899           12.48            79.69       4.70  
1480           12.17            83.66       4.13  
904            16.36            62.37       4.07  
1442           11.59            61.95       5.46  

[2400 rows x 9 columns]

In [279]:
data.value_counts()

ph         Hardness    Solids        Chloramines  Sulfate     Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability
5.530055   207.998220  38918.778073  6.543134     360.070715  427.664302    18.813080       61.214979        3.327472   1             7
7.736313   225.063103  19496.848592  7.158343     289.945985  433.974022    15.153817       74.765101        3.700917   1             6
6.791993   210.407967  30471.929098  6.614438     326.585846  493.179417    19.985555       61.120143        2.914057   1             5
6.640863   215.060867  16488.047656  6.642337     304.757434  507.128833    11.979157       18.015272        4.708269   1             5
6.008974   225.080234  5100.094173   7.452236     336.119000  325.134492    11.079952       36.341012        4.012340   1             5
                                                                                                                                     ..
6.532097   163.396241  8240.812709   6.641543     402

In [280]:
data.Potability.value_counts()

1    1200
0    1200
Name: Potability, dtype: int64

In [281]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# features= X.columns
# X[features] = sc.fit_transform(X[features])

In [282]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)
rf = RandomForestClassifier()
params_rf = {'n_estimators':[100,200, 350, 500], 'min_samples_leaf':[2, 10, 30]}
grid_rf = GridSearchCV(rf, param_grid=params_rf, cv=5)
grid_rf.fit(X_train, y_train)
print("Best parameters for Random Forest:", grid_rf.best_params_)

Best parameters for Random Forest: {'min_samples_leaf': 2, 'n_estimators': 350}


In [290]:
rf = RandomForestClassifier(n_estimators=350, min_samples_leaf=2, random_state=100)

In [291]:
from sklearn.metrics import accuracy_score ,confusion_matrix , classification_report , r2_score

rf.fit(X_train, y_train)    
   
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)

print(accuracy)

0.8375


In [292]:
rf.predict([[0,0,0,0,0,0,0,0,0]])

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0])

In [293]:
# True Positive , True Negative.....
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)

[[189  35]
 [ 43 213]]


In [294]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.84      0.83       224
           1       0.86      0.83      0.85       256

    accuracy                           0.84       480
   macro avg       0.84      0.84      0.84       480
weighted avg       0.84      0.84      0.84       480



In [295]:
print(r2_score(y_test,y_pred))

0.3470982142857143


In [296]:
#Saving the trained model

In [297]:
import pickle

In [298]:
filename='trained_final.sav'
pickle.dump(rf,open(filename,'wb'))

In [299]:
#loading the saved model

In [300]:
loaded_model = pickle.load(open('trained_final.sav','rb'))

In [301]:
# input_data =(7.7,200.22,17000.234343,7.72345,356.434345,500.32545,10.343434,100.324343,3.5353434)
# input_data =(7.423088,210.046197,31073.03133,6.374709, 312.103161, 460.894212, 16.805990, 41.607907 ,3.712682)
# input_data =(11.491011,94.812545,37188.826022,9.263166,258.930600,439.893618,16.172755,41.558501,4.369264	)
input_data =(7.754884, 210.720769 ,18857.058497, 5.693752 ,376.484622 ,375.672691 ,14.708599 ,43.299820 ,5.128390)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction=loaded_model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
  print("The water is not suitable for drinking")
else:
  print("The water is suitable for drinking")

[1]
The water is suitable for drinking


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
# input_data =(7.7,200.22,17000.234343,7.72345,356.434345,500.32545,10.343434,100.324343,3.5353434)
input_data =(7.808856,193.553212,17329.802160,8.061362,333.775777,392.449580,19.903225,66.396293,2.798243)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction=loaded_model.predict(input_data_reshaped)
print(prediction)

if(prediction[0]==0):
  print("The water is not suitable for drinking")
else:
  print("The water is suitable for drinking")

[0]
The water is not suitable for drinking


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
lst=loaded_model.predict_proba([[7.710960,181.938126,6552.626314,5.389249,390.596392,516.284083,17.010785,58.241734,4.288947]])[0]
lst=lst.tolist()
index=max(lst)
prediction = lst.index(index)
print(prediction)
if prediction==0:
  print("Not Suitable")
else:
  print("Suitable")

0
Not Suitable


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
